service: unitemate
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  region: ap-northeast-1
  stackName: ${sls:stage}-${self:service}-stack
  deploymentBucket:
    name: ${self:service}.sls-deployment-store
    maxPreviousDeploymentArtifacts: 3
  logRetentionInDays: 7

package:
  individually: true
  patterns:
    - "!**"
    - src/**
    - pyproject.toml
    - poetry.lock

functions:
  hello:
    handler: app/hello.handle

plugins:
  - serverless-python-requirements
  - serverless-prune-plugin
